apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    run: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    run: jenkins
  template:
    metadata:
      labels:
        run: jenkins
    spec:
      volumes:
        -  name: jenkins-home-volume
           emptyDir: {}
      containers:
      - image: jenkins/jenkins:lts-alpine
        name: jenkins
        volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home-volume
  test: false
  triggers: null

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: jenkins
  name: jenkins
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: jenkins
  type: NodePort

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    run: jenkins
  name: jenkins
spec:
  host: ""
  tls:
    termination: edge
  to:
    kind: ""
    name: jenkins
    weight: null
